import type { Character, FixedSkill } from '../types/character'

export const SKILL_LABELS: Record<keyof Character['skills'], string> = {
  acrobatics: 'Acrobatics (AGL)',
  awareness: 'Awareness (INT)',
  bartering: 'Bartering (CHA)',
  beastLore: 'Beast Lore (INT)',
  bluffing: 'Bluffing (CHA)',
  bushcraft: 'Bushcraft (INT)',
  crafting: 'Crafting (STR)',
  evade: 'Evade (AGL)',
  healing: 'Healing (INT)',
  huntingFishing: 'Hunting & Fishing (AGL)',
  languages: 'Languages (INT)',
  mythsLegends: 'Myths & Legends (INT)',
  performance: 'Performance (CHA)',
  persuasion: 'Persuasion (CHA)',
  riding: 'Riding (AGL)',
  seamanship: 'Seamanship (INT)',
  sleightOfHand: 'Sleight of Hand (AGL)',
  sneaking: 'Sneaking (AGL)',
  spotHidden: 'Spot Hidden (INT)',
  swimming: 'Swimming (AGL)',
}

export const WEAPON_SKILL_LABELS: Record<keyof Character['weaponSkills'], string> = {
  axes: 'Axes (STR)',
  bows: 'Bows (AGL)',
  brawling: 'Brawling (STR)',
  crossbows: 'Crossbows (AGL)',
  hammers: 'Hammers (STR)',
  knives: 'Knives (AGL)',
  slings: 'Slings (AGL)',
  spears: 'Spears (STR)',
  staves: 'Staves (AGL)',
  swords: 'Swords (STR)',
}

export function createBlankCharacter(): Omit<Character, 'id' | 'updatedAt'> {
  return {
    name: '',
    kin: '',
    profession: '',
    age: '',
    weakness: '',
    appearance: '',
    memento: '',
    abilities: '',
    attributes: { str: 0, con: 0, agl: 0, int: 0, wil: 0, cha: 0 },
    conditions: {
      exhausted: false,
      sickly: false,
      dazed: false,
      angry: false,
      scared: false,
      disheartened: false,
    },
    hitPoints: 0,
    maxHitPoints: 0,
    willpowerPoints: 0,
    maxWillpowerPoints: 0,
    movement: 0,
    damageBonusStr: '',
    damageBonusAgl: '',
    encumbranceLimit: 0,
    deathRolls: { successes: 0, failures: 0 },
    coins: { gold: 0, silver: 0, copper: 0 },
    skills: {
      acrobatics: { value: 0, marked: false },
      awareness: { value: 0, marked: false },
      bartering: { value: 0, marked: false },
      beastLore: { value: 0, marked: false },
      bluffing: { value: 0, marked: false },
      bushcraft: { value: 0, marked: false },
      crafting: { value: 0, marked: false },
      evade: { value: 0, marked: false },
      healing: { value: 0, marked: false },
      huntingFishing: { value: 0, marked: false },
      languages: { value: 0, marked: false },
      mythsLegends: { value: 0, marked: false },
      performance: { value: 0, marked: false },
      persuasion: { value: 0, marked: false },
      riding: { value: 0, marked: false },
      seamanship: { value: 0, marked: false },
      sleightOfHand: { value: 0, marked: false },
      sneaking: { value: 0, marked: false },
      spotHidden: { value: 0, marked: false },
      swimming: { value: 0, marked: false },
    },
    weaponSkills: {
      axes: { value: 0, marked: false },
      bows: { value: 0, marked: false },
      brawling: { value: 0, marked: false },
      crossbows: { value: 0, marked: false },
      hammers: { value: 0, marked: false },
      knives: { value: 0, marked: false },
      slings: { value: 0, marked: false },
      spears: { value: 0, marked: false },
      staves: { value: 0, marked: false },
      swords: { value: 0, marked: false },
    },
    secondarySkills: [],
    weapons: [],
    armor: {
      name: '',
      rating: null,
      banes: { sneaking: false, evade: false, acrobatics: false },
    },
    helmet: {
      name: '',
      rating: null,
      banes: { awareness: false, rangedAttacks: false },
    },
    inventory: [],
    tinyItems: [],
  }
}
