import type { Character } from '../types/character'

export function createBlankCharacter(): Omit<Character, 'id' | 'updatedAt'> {
  return {
    name: '',
    kin: '',
    profession: '',
    age: '',
    weakness: '',
    appearance: '',
    memento: '',
    abilities: '',
    attributes: { str: 0, con: 0, agl: 0, int: 0, wil: 0, cha: 0 },
    conditions: {
      exhausted: false,
      sickly: false,
      dazed: false,
      angry: false,
      scared: false,
      disheartened: false,
    },
    hitPoints: 0,
    maxHitPoints: 0,
    willpowerPoints: 0,
    maxWillpowerPoints: 0,
    movement: 0,
    damageBonusStr: '',
    damageBonusAgl: '',
    encumbranceLimit: 0,
    deathRolls: { successes: 0, failures: 0 },
    coins: { gold: 0, silver: 0, copper: 0 },
    skills: {
      acrobatics: { label: 'Acrobatics (AGL)', value: 0, marked: false },
      awareness: { label: 'Awareness (INT)', value: 0, marked: false },
      bartering: { label: 'Bartering (CHA)', value: 0, marked: false },
      beastLore: { label: 'Beast Lore (INT)', value: 0, marked: false },
      bluffing: { label: 'Bluffing (CHA)', value: 0, marked: false },
      bushcraft: { label: 'Bushcraft (INT)', value: 0, marked: false },
      crafting: { label: 'Crafting (STR)', value: 0, marked: false },
      evade: { label: 'Evade (AGL)', value: 0, marked: false },
      healing: { label: 'Healing (INT)', value: 0, marked: false },
      huntingFishing: {
        label: 'Hunting & Fishing (AGL)',
        value: 0,
        marked: false,
      },
      languages: { label: 'Languages (INT)', value: 0, marked: false },
      mythsLegends: { label: 'Myths & Legends (INT)', value: 0, marked: false },
      performance: { label: 'Performance (CHA)', value: 0, marked: false },
      persuasion: { label: 'Persuasion (CHA)', value: 0, marked: false },
      riding: { label: 'Riding (AGL)', value: 0, marked: false },
      seamanship: { label: 'Seamanship (INT)', value: 0, marked: false },
      sleightOfHand: {
        label: 'Sleight of Hand (AGL)',
        value: 0,
        marked: false,
      },
      sneaking: { label: 'Sneaking (AGL)', value: 0, marked: false },
      spotHidden: { label: 'Spot Hidden (INT)', value: 0, marked: false },
      swimming: { label: 'Swimming (AGL)', value: 0, marked: false },
    },
    weaponSkills: {
      axes: { label: 'Axes (STR)', value: 0, marked: false },
      bows: { label: 'Bows (AGL)', value: 0, marked: false },
      brawling: { label: 'Brawling (STR)', value: 0, marked: false },
      crossbows: { label: 'Crossbows (AGL)', value: 0, marked: false },
      hammers: { label: 'Hammers (STR)', value: 0, marked: false },
      knives: { label: 'Knives (AGL)', value: 0, marked: false },
      slings: { label: 'Slings (AGL)', value: 0, marked: false },
      spears: { label: 'Spears (STR)', value: 0, marked: false },
      staves: { label: 'Staves (AGL)', value: 0, marked: false },
      swords: { label: 'Swords (STR)', value: 0, marked: false },
    },
    secondarySkills: [],
    weapons: [],
    armor: {
      name: '',
      rating: null,
      banes: { sneaking: false, evade: false, acrobatics: false },
    },
    helmet: {
      name: '',
      rating: null,
      banes: { awareness: false, rangedAttacks: false },
    },
    inventory: [],
    tinyItems: [],
  }
}
